spring:
  application:
    name: catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8585
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Lima
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB